---
- name: Install and Configure TDengine Cluster on Ubuntu
  hosts: tdengine_cluster
  become: yes
  vars:
    tdengine_version: "3.2.2.0"
    tdengine_package_url: "https://www.tdengine.com/assets-download/3.0/TDengine-server-{{ tdengine_version }}-Linux-x64.deb"
    tdengine_service_name: taosd

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      changed_when: false

    - name: Download TDengine Debian package
      get_url:
        url: "{{ tdengine_package_url }}"
        dest: "/tmp/TDengine.deb"
      register: download_result
      until: download_result is succeeded
      retries: 3
      delay: 5

    - name: Ensure 'expect' is installed
      apt:
        name: expect
        state: present

  
    - name: Install TDengine with expect to handle prompts
      expect:
        command: dpkg -i /tmp/TDengine.deb
        responses:
          Enter FQDN:port \(like h1.taosdata.com:6030\) of an existing TDengine cluster node to join: ""
          Enter your email address for priority support or enter empty to skip: ""
      become: yes

    - name: Get the public IP address of the first node
      shell: hostname -I | awk '{print $1}'
      register: public_ip
      when: inventory_hostname == groups['tdengine_cluster'][0]
      delegate_to: "{{ groups['tdengine_cluster'][0] }}"

    - name: Configure TDengine cluster
      blockinfile:
        path: /etc/taos/taos.cfg
        block: |
          # The FQDN of the host on which this dnode will be started. It can be IP address
          fqdn                    {{ public_ip.stdout | default(ansible_host) }}

          # The port for external access after this dnode is started
          serverPort                6030

          {% if inventory_hostname == groups['tdengine_cluster'][0] %}
          firstEp {{ public_ip.stdout }}:6030
          {% else %}
          firstEp {{ hostvars[groups['tdengine_cluster'][0]].ansible_host }}:6030
          secondEp {{ ansible_host }}:6030
          {% endif %}
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
      when: inventory_hostname in groups['tdengine_cluster']


    - name: Start and enable TDengine Service
      systemd:
        name: "{{ tdengine_service_name }}"
        state: started
        enabled: yes

  handlers:
    - name: restart tdengine
      systemd:
        name: "{{ tdengine_service_name }}"
        state: restarted
        enabled: yes
